image: docker:stable
variables:
  GIT_SSL_NO_VERIFY: "true"

# services:
#   - docker:dind

before_script:
- apk add --no-cache py2-pip && pip install docker-compose

- docker info
- docker-compose --version

build:
  stage: build
  script:
  - docker build -t wechat-bot .
  - docker-compose up -d