image: linhaobin/docker-compose
variables:
  GIT_SSL_NO_VERIFY: "true"

before_script:
- docker info
- docker-compose --version

build:
  stage: build
  script:
  - docker build -t wechat-bot .
  - docker-compose up -d