version: "3.5"

services:
  app:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 7001:7001
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
    networks: 
      - wechat-bot
    environment:
      # - WECHATY_LOG=verbose
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongo:27017/wechat-bot
      - REDIS_HOST=redis

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks: 
      wechat-bot:
        aliases:
          - mongo

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks: 
      wechat-bot:
        aliases:
          - redis

volumes:
  mongodb:
    name: wechat-bot_mongodb
  redis:
    name: wechat-bot_redis
  node_modules:
    name: wechat-bot_node_modules

networks: 
  wechat-bot:
    name: wechat-bot