version: "3.5"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  mongodb:
    name: wechat-bot_mongodb
  redis:
    name: wechat-bot_redis